stages:
  - androidbuild
  - androidtest 
  
android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
   - keenan_tag                   # <-- change to your runner's tag
  before_script:                    
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend                   
    - ./gradlew build

android-test:
   image: afirefly/android-ci:java17
   stage: androidtest
   tags:
    - keenan_tag                  # <-- change to your runner's tag
   before_script:                  
     - export GRADLE_USER_HOME=`pwd`/.gradle
     - chmod +x ./Frontend/gradlew
   script:
     - cd /Frontend                
     - ./gradlew test
